name: NetherSpells
main: com.elmakers.mine.bukkit.plugins.nether.spells.NetherSpellsPlugin
version: 0.10
website: http://mine.elmakers.com
author: NathanWolf
description : Magic/NetherGate integration
depend:
 - Persistence
 - NetherGate
 - Magic